version: "3.9"
services:
    pngwriter:
        build: .
        tty: true
        stdin_open: true
    
    build_test:
        build: 
            context: .
            dockerfile: Dockerfile_buildtest
        volumes:
            - .:/workspace
        stdin_open: true
        tty: true
        command: /bin/bash
    